# Generated by Django 3.2.2 on 2024-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='xxxxxx@email.com', max_length=32, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
